"""empty message

Revision ID: 1e39dce2b0fb
Revises: 719802a73890
Create Date: 2018-10-18 11:20:30.236405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e39dce2b0fb'
down_revision = '719802a73890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mail', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mail')
    # ### end Alembic commands ###
