"""empty message

Revision ID: 6ed4914834de
Revises: 7df24d455475
Create Date: 2018-10-18 12:21:33.197124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed4914834de'
down_revision = '7df24d455475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_password', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_password', 'user', ['password'], unique=True)
    # ### end Alembic commands ###
