"""empty message

Revision ID: 7172f18a986a
Revises: 916e34c34845
Create Date: 2018-10-18 16:13:42.329367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7172f18a986a'
down_revision = '916e34c34845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sorts', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sorts', 'store', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sorts', type_='foreignkey')
    op.drop_column('sorts', 'store_id')
    # ### end Alembic commands ###
