"""empty message

Revision ID: 719802a73890
Revises: c1b000440d70
Create Date: 2018-10-15 15:38:12.883717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '719802a73890'
down_revision = 'c1b000440d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('packing_ibfk_1', 'packing', type_='foreignkey')
    op.drop_column('packing', 'currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packing', sa.Column('currency', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('packing_ibfk_1', 'packing', 'currency', ['currency'], ['id'])
    # ### end Alembic commands ###
