"""empty message

Revision ID: 72b57019c032
Revises: 7172f18a986a
Create Date: 2018-10-22 20:49:13.580041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b57019c032'
down_revision = '7172f18a986a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'store', ['store_id'], ['id'])
    op.create_foreign_key(None, 'products', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    op.drop_column('products', 'store_id')
    op.drop_column('products', 'create_date')
    # ### end Alembic commands ###
