"""empty message

Revision ID: 7df24d455475
Revises: 1e39dce2b0fb
Create Date: 2018-10-18 11:58:48.754806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df24d455475'
down_revision = '1e39dce2b0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_mail'), 'user', ['mail'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mail'), table_name='user')
    # ### end Alembic commands ###
